# Birds CUB dataset
birds_images_path: '/home/projet11/export/aelnouby/Birds dataset/CUB_200_2011/'
birds_embedding_path: '/home/projet11/export/aelnouby/Birds dataset/cub_icml/'
birds_text_path: '/home/projet11/export/aelnouby/Birds dataset/cvpr2016_cub/text_c10/'
birds_dataset_path: '/home/projet11/data/oiseaux/birds.hdf5'
val_split_path: '/home/projet11/export/aelnouby/Birds dataset/cub_icml/valclasses.txt'
train_split_path: '/home/projet11/export/aelnouby/Birds dataset/cub_icml/trainclasses.txt'
test_split_path: '/home/projet11/export/aelnouby/Birds dataset/cub_icml/testclasses.txt'


# flowers dataset
flowers_images_path: '/home/projet11/export/aelnouby/flowers_dataset/'
flowers_embedding_path: '/home/projet11/export/aelnouby/flowers_dataset/flowers_icml/'
flowers_text_path: '/home/projet11/export/aelnouby/flowers_dataset/cvpr2016_flowers/text_c10/'
flowers_dataset_path: '/home/projet11/data/fleurs/flowers.hdf5'

flowers_val_split_path: '/home/projet11/export/aelnouby/flowers_dataset/flowers_icml/valclasses.txt'
flowers_train_split_path: '/home/projet11/export/aelnouby/flowers_dataset/flowers_icml/trainclasses.txt'
flowers_test_split_path: '/home/projet11/export/aelnouby/flowers_dataset/flowers_icml/testclasses.txt'
